-- AlterTable
ALTER TABLE "dpr_chainages" ALTER COLUMN "quantity" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "plan_quantity" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "boq_rate" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "amount" SET DATA TYPE DOUBLE PRECISION;
