import prisma from './config/prisma';
export * from './schema/user';
export * from './schema/admin';
export * from './schema/mail';
export * from './schema/otp';
export * from './schema/file';
export * from './schema/project';
export * from './schema/dpr';
export * from './schema/grn';
export * from './schema/po';
export * from './schema/pr';
export * from './schema/category';
export * from './schema/chainage';
export * from './schema/diesel';
export * from './schema/labour';
export * from './schema/material';
export * from './schema/modules';
export * from './schema/permission';
export * from './schema/role';
export * from './schema/sub_contractor';
export * from './schema/unit';
export * from './schema/vendor';
export * from './schema/vendor_supply_management';
export * from './schema/enums';
export { allModels } from './schema';
export * from './lib/tools';
export * from './lib/env';

export { prisma };
export default prisma;
