import prisma from './config/prisma';
export * from './schema/user';
export * from './schema/mail';
export * from './schema/otp';
export * from './schema/file';
export * from './schema/project';
export * from './schema/dpr';
export * from './schema/grn';
export * from './schema/po';
export * from './schema/pr';
export * from './schema/category';
export * from './schema/chainage';
export * from './schema/diesel';
export * from './schema/labour';
export * from './schema/material';
export * from './schema/modules';
export * from './schema/permission';
export * from './schema/role';
export * from './schema/unit';
export * from './schema/vendor';
export * from './schema/vendor_supply_management';
export * from './schema/enums';
export * from './schema/location';
export * from './schema/invoice';
export * from './schema/activity';
export * from './schema/stock';
export * from './schema/pr-grn';
export * from './schema/labour_attendance';
export * from './schema/material_boq';
export * from './schema/workscope';
export * from './schema/ProjectType';
export * from './schema/project_category';
export { allModels } from './schema';
export * from './lib/tools';
export * from './lib/env';

export { prisma };
export default prisma;
